{% set name = "deepchecks" %}
{% set version = "0.8.3" %}
{% set sha256 = "71ba902d127d2e0933a6a12208e6745f77f4f27c5836e83f29376af095eb8186" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepchecks-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pandas >=1.1.5
    - numpy >=1.19
    - scikit-learn >=0.23.2
    - jsonpickle >=2
    - pynomaly >=0.3.3
    - ipython >=7.15.0,<8    # [py>=38]
    - ipython >=5.5.0,<8     # [py<38]
    - ipykernel >=5.3.0      # [py>=38]
    - ipykernel >=4.10.1     # [py<38]
    - ipywidgets >=7.6.5,<8  # [py>=38]
    - ipywidgets >=7.5.0,<8  # [py<38]
    - typing_extensions >=3.7.4.3
    - tqdm >=4.62.3
    - category_encoders >=2.3.0
    - importlib_resources >=1.3  # [py<39]
    - importlib_metadata >=1.4  # [py<38]
    - statsmodels >=0.11.0
    - dataclasses >=0.6  # [py<37]
    # defaults does not have plotly 5.5.0. The
    # best we can do is lower-bound it
    - plotly >=5.5.0
    - matplotlib-base >=3.3.4
test:
  imports:
    - deepchecks
  commands:
    # pip check will fail because of plotly
    - pip check || true  # [not win]
    - pip check || exit 0  # [win]
  requires:
    - pip
    - numpy <1.23

about:
  home: https://github.com/deepchecks/deepchecks
  license: AGPL-3.0-only 
  license_family: AGPL
  license_file: LICENSE
  summary: Testing and Validating ML Models & Data
  description: |
    Deepchecks is a Python package for comprehensively validating your machine
    learning models and data with minimal effort. This includes checks related
    to various types of issues, such as model performance, data integrity,
    distribution mismatches, and more.
  doc_url: https://docs.deepchecks.com/
  doc_source_url: https://github.com/deepchecks/deepchecks/tree/main/docs
  dev_url: https://github.com/deepchecks/deepchecks

extra:
  recipe-maintainers:
    - thewchan
