{% set name = "deepchecks" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepchecks-{{ version }}.tar.gz
  sha256: 6ed9fc418a4d02d0ea679214e7d114e1d7716be2ee6ccb5355c66496622f1a63

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - category_encoders >=2.3.0
    - dataclasses >=0.6
    - ipykernel >=5.3.0
    - ipython >=5.5.0
    - ipywidgets >=7.6.5
    - jsonpickle >=2
    - matplotlib-base >=3.2.2
    - numpy >=1.19
    - pandas >=1.1.5
    - plotly >=5.5.0
    - python >=3.6
    - scikit-learn >=0.24.2
    - scipy >=1.4.1
    - statsmodels >=0.11.0
    - tqdm >=4.62.3
    - typing-extensions >=3.7.4.3

test:
  source_files: tests
  imports:
    - deepchecks
    - deepchecks.base
    - deepchecks.checks
    - deepchecks.checks.distribution
    - deepchecks.checks.integrity
    - deepchecks.checks.methodology
    - deepchecks.checks.overview
    - deepchecks.checks.performance
    - deepchecks.datasets
    - deepchecks.datasets.regression
    - deepchecks.suites
    - deepchecks.utils
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests  # [not win]
  requires:
    - pip
    - pyhamcrest  # [not win]
    - pytest  # [not win]

about:
  home: https://github.com/deepchecks/deepchecks
  summary: Test Suites for Validating ML Models & Data
  doc_url: https://docs.deepchecks.com/
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
